title: Categories
modelClass: Stone\Products\Models\Category
list: $/stone/products/models/category/columns.yaml
recordUrl: 'stone/products/categories/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: false
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
